FROM nginx:1.13

ENV ftp_proxy http://proxy.cse.cuhk.edu.hk:8000
ENV http_proxy http://proxy.cse.cuhk.edu.hk:8000
ENV https_proxy http://proxy.cse.cuhk.edu.hk:8000

RUN apt-get update --fix-missing
RUN mkdir -p /usr/src/app/src

WORKDIR /usr/src/app

RUN apt-get install -y curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install -y nodejs

COPY package.json .
COPY package-lock.json .
COPY .browserslistrc .
COPY .postcssrc.js .
COPY vue.config.js .
COPY tsconfig.json .
COPY ag-client-typescript ag-client-typescript

RUN npm install

COPY . /usr/src/app
RUN npm run build

WORKDIR /etc/nginx
